- lib/generators/rolemodel/heroku/heroku_generator.rb
Every app should be using SSL in production, especially on Heroku.
This generator change relies on Rails' default version of `config/environments/production.rb`, and assumes `force_ssl` is already set to `true` when the no commented-out `config.force_ssl = true` line exists. If that assumption isn't safe to make, I can make this more robust.
> Update Heroku generator to enable force_ssl option in production

- lib/generators/rolemodel/linters/eslint/eslint_generator.rb
This typo broke any ESLint rules related to resolving imports, since the required webpack resolver plugin didn't get installed.
> Fix typo in ESLint generator

- lib/generators/rolemodel/heroku/templates/app.json.erb
This fixes an issue with heroku postdeploy command failing with 'potentially destructive action' error.
> Update heroku postdeploy command to fix an error on heroku

- lib/generators/rolemodel/css/README.md
- lib/generators/rolemodel/css/all_generator.rb
- lib/generators/rolemodel/css/icons/README.md
- lib/generators/rolemodel/css/icons/USAGE
- lib/generators/rolemodel/css/icons/icons_generator.rb
- lib/generators/rolemodel/css/icons/templates/app/helpers/icon_helper.rb
- lib/generators/rolemodel/css/icons/templates/app/javascript/stylesheets/components/icon.scss
Adds a generator for a basic icon setup using material-icons. This doesn't support custom icons, but that could be added in a future PR (or possibly in this PR).
Most implementations of this pattern have put the `icon` helper method in `ApplicationHelper`. I opted to move this to its own helper file to reduce generator complexity and potential conflicts (I've tried this in an app and Rails does pick up the helper file).
> Add icons generator

- README.md
- lib/generators/rolemodel/all_generator.rb
The `css:icons` generator needs to run after `webpacker`. Otherwise, its changes to `package.json` to install `material-icons` get overwritten. A reference to the icons generator was also missing from the top-level readme.
> Fix icons generator when running all generators

- lib/generators/rolemodel/testing/rspec/USAGE
- lib/generators/rolemodel/testing/rspec/rspec_generator.rb
- lib/generators/rolemodel/testing/rspec/templates/support/capybara_testid.rb
This adds configuration for Capybara to support the `data-testid` attribute like `react-testing-library` does. The naming for the attribute matches `react-testing-library`'s default.
> Configure Capybara to support data-testid attributes

- lib/generators/rolemodel/css/base/templates/app/javascript/stylesheets/components/semantic_backgrounds.scss
- lib/generators/rolemodel/css/base/templates/app/javascript/stylesheets/variables/dark_mode.scss
- lib/generators/rolemodel/css/base/templates/app/javascript/stylesheets/variables/semantic_color_scales.scss
- lib/generators/rolemodel/css/base/templates/app/views/styleguide/index.html.slim
[TR #76](https://trello.com/c/fRWGaCc9/76-e48-neutral-semantic-scales)
Added neutral semantic scales for greater flexibility with styling.
> [TR #76] add-neutral-semantic-scales

- lib/generators/rolemodel/css/base/templates/app/javascript/stylesheets/components/button.scss
- lib/generators/rolemodel/css/base/templates/app/javascript/stylesheets/components/card.scss
- lib/generators/rolemodel/css/base/templates/app/javascript/stylesheets/components/form.scss
- lib/generators/rolemodel/css/base/templates/app/javascript/stylesheets/components/swatch.scss
- lib/generators/rolemodel/css/base/templates/app/javascript/stylesheets/components/table.scss
- lib/generators/rolemodel/css/base/templates/app/javascript/stylesheets/variables/dark_mode.scss
- lib/generators/rolemodel/css/base/templates/app/javascript/stylesheets/variables/semantic_color_scales.scss
- lib/generators/rolemodel/modals/templates/app/javascript/stylesheets/components/modal.scss
- lib/generators/rolemodel/modals/templates/app/javascript/stylesheets/components/panel.scss
[TR #77](https://trello.com/c/Nnsc49kY/77-e48-convert-surface-colors-to-background-colors)
Surface and background are synonymous and we don't need specific names for them when we can use semantic scales.
> [TR #77] convert-surface-colors-to-background-colors

- lib/generators/rolemodel/heroku/heroku_generator.rb
This adds to the Heroku generator a step to modify the `production.rb` file to allow the use of `LOG_LEVEL` env var to configure the production Rails log level.
> Add production.rb log level config via ENV Var

- lib/generators/rolemodel/css/base/templates/app/javascript/stylesheets/base.scss
- lib/generators/rolemodel/css/base/templates/app/javascript/stylesheets/components/button.scss
- lib/generators/rolemodel/css/base/templates/app/javascript/stylesheets/variables/semantic_color_scales.scss
- lib/generators/rolemodel/css/base/templates/app/javascript/stylesheets/variables/tokens.scss
[TR #58](https://trello.com/c/DyO1hBwF)
Structure the file using a `%btn` with base styles that extend `%btn` for button variants. Also, some of our button variants were outdated and needed some cleanup.
Old:
New:
> [TR #58] Buttons Revisited

- lib/generators/rolemodel/css/base/templates/app/javascript/stylesheets/utilities.scss
[TR #81](https://trello.com/c/r7I7rdwk)
The layout-row utility was overloaded and doing more than it should have.
It needs to be simplified and a new concept `flexible-layout-area` needs to be added to clearly separate the concepts and add documentation.
> [TR #81] Add separate concepts for layout row and flexible layout area

- lib/generators/rolemodel/css/icons/templates/config/webpack/loaders/svg-color-override-loader.js
In an app I realized that the clip path ids were being optimized to the same thing no matter if they were different in the file definition.
Before
After
> Fix Custom Icon Clip Paths

- lib/generators/rolemodel/linters/rubocop/rubocop_generator.rb
- lib/generators/rolemodel/linters/rubocop/templates/.rubocop.yml
When the app tries to deploy, if the `rubocop` gem is `:development, :test`, Rails tries to load the `cops` folder which then looks for the Rubocop class, which doesn't exist. This moves the Cop to live under `lib` so that doesn't happen.
> Move Custom Cop to Lib

- lib/generators/rolemodel/simple_form/templates/config/initializers/simple_form.rb
[TR #XXX]()
Initializer does not work with the latest Optics. After spending some time configuring on a project I learned that the latest configuration was found in Methodist Home.
Before
After
> incorporate latest simple form initializer

- lib/generators/rolemodel/semaphore/templates/semaphore.yml.erb
This flag is not relevant anymore because it does nothing. All new projects don't need this set.
> Remove Semaphore --expire-in Flag

- README.md
- lib/generators/rolemodel/all_generator.rb
- lib/generators/rolemodel/kaminari/README.md
- lib/generators/rolemodel/kaminari/USAGE
- lib/generators/rolemodel/kaminari/kaminari_generator.rb
- lib/generators/rolemodel/kaminari/templates/app/views/kaminari/_first_page.html.slim
- lib/generators/rolemodel/kaminari/templates/app/views/kaminari/_gap.html.slim
- lib/generators/rolemodel/kaminari/templates/app/views/kaminari/_last_page.html.slim
- lib/generators/rolemodel/kaminari/templates/app/views/kaminari/_next_page.html.slim
- lib/generators/rolemodel/kaminari/templates/app/views/kaminari/_page.html.slim
- lib/generators/rolemodel/kaminari/templates/app/views/kaminari/_paginator.html.slim
- lib/generators/rolemodel/kaminari/templates/app/views/kaminari/_prev_page.html.slim
- lib/generators/rolemodel/optics/all_generator.rb
[Kaminari](https://github.com/kaminari/kaminari) is a tool we commonly use for paginating data. Optics is adding some styling around pagination so this generator configures your application to use the correct styling.
This relies on https://github.com/RoleModel/optics/pull/175 which is not released yet. It should be fine for the time being though
> Add Kaminari

- lib/generators/rolemodel/modals/templates/app/helpers/turbo_frame_link_helper.rb
- lib/rolemodel_rails/version.rb
Fix Issue #109 
modal_link_to & panel_link_to required 2 arguments, while link_to only requires 1.
> modal_link_to optional second argument (fix #109)

- Gemfile.lock
- lib/generators/rolemodel/modals/modals_generator.rb
- lib/generators/rolemodel/modals/templates/app/views/layouts/modal.html.slim.tt
- lib/rolemodel_rails/version.rb
Fix modal issues noted in #100 
The modals generator was not pointing to the correct files and the template was not up to date.
Since Optics provides the modal as a full component now instead of an addon, these needed to be updated.
There might be a future PR to start using the `dialog` element, but there is further discussion needed on it.
> Modals Generator

- README.md
- lib/generators/rolemodel/testing/rspec/templates/rails_helper.rb
There is a very confusing side affect when you run `rails new` with `--skip-test` (since we use Rspec instead). In the latest versions of rails it will cause system tests to throw the following error
```shell
Unrecognized command "test:prepare" (Rails::Command::UnrecognizedCommandError)
Did you mean?  test:helpers
```
Using `--skip-test` generates `config/application.rb` with
```ruby
require_relative "boot"
require "rails"
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_mailbox/engine"
require "action_text/engine"
require "action_view/railtie"
require "action_cable/engine"
```
Notice that last commented out line...
If you don't …
> Fix Rspec rails helper asset precompile step

- lib/generators/rolemodel/mailers/templates/config/initializers/premailer_rails.rb
The default regex given to remove CSS Custom Properties before passing CSS to Premailer-Rails failed to fully match some complex syntaxes, and corrupted the resulting stylesheet.
```css
--op-encoded-images-dropdown-arrow: url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTIiIGhlaWdodD0iOSIgdmlld0JveD0iMCAwIDEyIDkiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxwYXRoIGQ9Ik02IDguMzc1MDFMMCAyLjM3NTAxTDEuNCAwLjk3NTAwNkw2IDUuNTc1MDFMMTAuNiAwLjk3NTAwNkwxMiAyLjM3NTAxTDYgOC4zNzUwMVoiIGZpbGw9IiMwQTBBMEIiLz4KPC9zdmc+Cg==");
```
```css
--op-input-focus-primary: var(--op-input-inner-focus) var(--op-color-primary-plus-two),
var(--op-input-outer-focus) var(--op-color-primary-plus-five);
```
> Improve Premailer initializer to avoid breaking premailer when using Optics

- lib/generators/rolemodel/testing/rspec/rspec_generator.rb
- lib/generators/rolemodel/testing/rspec/templates/support/helpers.rb
- lib/generators/rolemodel/testing/rspec/templates/support/helpers/action_cable_helper.rb
With the launch of Turbo 8, capybara was having issues testing features that leverage action cable. This new helper forces capybara to delay its proceeding expectations until after the action cable connection has been established by the page.
> Add ActionCableHelper file and include it in helpers.rb and rspec_generator.rb

- lib/generators/rolemodel/modals/templates/app/views/layouts/panel.html.slim.tt
See https://rolemodelsoftware.slack.com/archives/C051DL755/p1730914751683569?thread_ts=1718918599.340109&cid=C051DL755
See https://github.com/rack/rack/pull/2137
> Make modal compatible with Rack 3.1

- .github/pull_request_template.md
- lib/generators/rolemodel/github/templates/pull_request_template.md
Why were the changes needed? What issues were the changes addressing?
(Note: some changes may seem unrelated to the ticket, this is a great place to explain further.)
Linear automatically links to the PR when referenced in the PR name; READMEs are hard to remember to update to confirm they get updated upon PR creation/review
If any UI changes need to be shown off, please add screenshots here.
> Update Github pull_request_template.md to include README update, remove Task section

- lib/generators/rolemodel/modals/templates/app/javascript/controllers/toggle_controller.js
- lib/generators/rolemodel/modals/templates/app/views/layouts/modal.html.slim.tt
- lib/generators/rolemodel/modals/templates/app/views/layouts/panel.html.slim.tt
- spec/generators/rolemodel/modals_generator_spec.rb
Remote content is still included in the tab index, even if off screen and not scrollable into view. This is relevant when modal or panels are dismissed but still have contents within them. This change allows the [inert](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert) data attribute to be toggle along with the active class. This makes the contents non interactive. This makes them both more usable and more accessible.
https://github.com/user-attachments/assets/dc5d068e-7ba2-4e04-b673-93ade9e91153
> toggle controller inert attribute

- lib/generators/rolemodel/lograge/templates/config/initializers/lograge.rb
The previous configuration was broken because the controller was not available in the context
If any UI changes need to be shown off, please add screenshots here.
> fix controller logging, always use lograge

- Gemfile.lock
- lib/generators/rolemodel/source_map/README.md
- lib/generators/rolemodel/source_map/USAGE
- lib/generators/rolemodel/source_map/source_map_generator.rb
- lib/generators/rolemodel/source_map/templates/lib/middleware/rolemodel/source_map.rb
- lib/generators/rolemodel/source_map/templates/lib/tasks/assets.rake
- lib/rolemodel_rails/version.rb
- spec/generators/rolemodel/source_map_generator_spec.rb
The recommended approach to relocating source maps breaks under Propshaft, because Propshaft removes source map URLs if it can't find the source map files. Instead of relying on the build (webpack) to relocate source maps, this takes the approach of enhancing the Rails assets rake tasks to manage source map files.
> Improve source map generator

- Gemfile.lock
- lib/generators/rolemodel/linters/rubocop/README.md
- lib/generators/rolemodel/linters/rubocop/rubocop_generator.rb
- lib/generators/rolemodel/linters/rubocop/templates/.rubocop.yml
- lib/generators/rolemodel/linters/rubocop/templates/lib/cops/form_error_response.rb
- lib/generators/rolemodel/linters/rubocop/templates/lib/cops/no_chrome_tag.rb
- lib/rolemodel_rails/version.rb
- rolemodel_rails.gemspec
- spec/cops/form_error_response_spec.rb
- spec/cops/no_chrome_tag_spec.rb
- spec/generators/rolemodel/rubocop_generator_spec.rb
Looking for :chrome tags in specs is tedious. This will automate highlighting and removing those.
> Add no_chrome_tag to rubocop generator

- lib/generators/rolemodel/saas/devise/devise_generator.rb
- lib/generators/rolemodel/saas/devise/templates/app/assets/stylesheets/login.css
- lib/generators/rolemodel/saas/devise/templates/app/views/devise/confirmations/new.html.slim
- lib/generators/rolemodel/saas/devise/templates/app/views/devise/invitations/edit.html.slim
- lib/generators/rolemodel/saas/devise/templates/app/views/devise/invitations/new.html.slim
- lib/generators/rolemodel/saas/devise/templates/app/views/devise/passwords/edit.html.slim
- lib/generators/rolemodel/saas/devise/templates/app/views/devise/passwords/new.html.slim
- lib/generators/rolemodel/saas/devise/templates/app/views/devise/registrations/edit.html.slim
- lib/generators/rolemodel/saas/devise/templates/app/views/devise/registrations/new.html.slim
- lib/generators/rolemodel/saas/devise/templates/app/views/devise/sessions/new.html.slim
- lib/generators/rolemodel/saas/devise/templates/app/views/devise/shared/_error_messages.html.slim
- lib/generators/rolemodel/saas/devise/templates/app/views/devise/shared/_links.html.slim
- lib/generators/rolemodel/saas/devise/templates/app/views/devise/unlocks/new.html.slim
- lib/generators/rolemodel/testing/rspec/templates/spec_helper.rb
The Devise forms always look terrible and need customizing. Optics docs already have a recommended pattern for login forms: https://docs.optics.rolemodel.design/?path=/docs/recipes-layout--docs&globals=theme:dark
> Update devise forms

- lib/generators/rolemodel/testing/parallel_tests/README.md
- lib/generators/rolemodel/testing/parallel_tests/USAGE
- lib/generators/rolemodel/testing/parallel_tests/parallel_tests_generator.rb
- lib/generators/rolemodel/testing/parallel_tests/templates/.rspec_parallel
- spec/generators/rolemodel/parallel_test_generator_spec.rb
I realized I forgot to add the `.rspec_parallel` file to the generator. I also wanted to add the `turbo_test` gem for optional use.
* ~[ ] Update version number in `lib/rolemodel_rails/version.rb`~
> Add rspec_parallel and Turbo Tests to Parallel RSpec Generator

- Gemfile.lock
- example_rails7/Gemfile
- example_rails7/Gemfile.lock
- example_rails8/Gemfile
- example_rails8/Gemfile.lock
- lib/generators/rolemodel/soft_destroyable/templates/soft_destroyable.rb
- lib/generators/rolemodel/soft_destroyable/templates/soft_destroyable_behavior.rb
- lib/rolemodel_rails/version.rb
When updating a soft destroyable record's attributes, it would attempt to save the record when soft destroying it. 
This would become a problem when other attributes, in addition to `_soft_destroy`, were being assigned. If any of those other attributes were invalid, it would fail to soft destroy the record.
This PR fixes that by overriding the `assign_attributes` method, which rails uses under the hood, to ignore all other attributes if `_soft_destroy` is present.
This is an existing record with a video link attachment. There are validations around the link being real.
WHEN: I edit the link to no longer be valid, then mark the record for soft destruction.
THEN: I attempt to save, but it gives an error saying the record is invalid and cannot be soft destroyed. …
> Add Assign Attributes Override to Soft Destroyable
